travis:
  secure:
    BINSTAR_TOKEN: UGN1SGth3rloUGiYfS6jUh18b31Ty3pKStkW6Kuqqq7AUs8niKcYcMmc/WL2UoV9Nv6nofKdwZVRRhjkL1tY7oj2BFTXAyKLMJy+zfN82xd8UqaVd5/7IOE6CmUAuTS54dHCu2KaCkzoHXCLBzLbv95TgpaE6m2PxmTlggxpiOTDtQk03aEEPh2tW+Bsen/bqcoBEQHLdAnBwxTkXg7glBecVDqG+2QsAVXPraZ2tUqrkDb6WeevhJdKORZwc+6BCGWdIdv6fVHPPO7/wKjAglLTlXD0QSVD/6+/qqdbVpCgZSVev2+bxkBeZSSdHqgESec2SAOBla8Sk7By3NXTtxiXl3M1HijpJQFq/G1NDlw5dIHwwFx3LNilEhwla55hJ+A5u3spL0ZQ3N1JmhKI1s8aQbrRBAAXIXxliX1j1tntQ7dT0WnZwkSS6QaRZWGLK8tremtdHgZKffMdY7BxR9s24SDiKG6p0PXujQeljyYT8j8IKlMbSp28pEhA8esjjflS0qm+gmEVNCDnFccT3jt8uvhRWLu24MDyu1MtVc30wGU92wdnmvQ8QcRFGK0UloCz2BRTOHqSAhpHwN4jpcusZco2ukTZrkB04x828XSYC+XLfU9/IPHHi6Vuj+Zwwp0ucgEBoYomyTB2MIKRLiCNEpvSjcg8skGk6VnHNF0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
